# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0003_post_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='display_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
